name: Run X Autopilot Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3,9 * * *'  # 12:00, 18:00 KST 기준 (UTC 기준)

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TW_API_KEY: ${{ secrets.TW_API_KEY }}
          TW_API_SECRET: ${{ secrets.TW_API_SECRET }}
          TW_ACCESS_TOKEN: ${{ secrets.TW_ACCESS_TOKEN }}
          TW_ACCESS_SECRET: ${{ secrets.TW_ACCESS_SECRET }}
          TW_CLIENT_ID: ${{ secrets.TW_CLIENT_ID }}
          TW_CLIENT_SECRET: ${{ secrets.TW_CLIENT_SECRET }}
          TW_BEARER_TOKEN: ${{ secrets.TW_BEARER_TOKEN }}
          TZ: Asia/Seoul
        run: python x_autopilot_agent.py
